version: '3'

services:
  xyz:
    container_name: xyz
    build:
      context: .
    image: xyz
    environment:
      NODE_ENV: production
      PORT: 3000
      LOG_LEVEL: log
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres-db
      DB_USER: postgres-user
      DB_PASSWORD: postgres-password
      RPC_URL: 'http://hardhat:8545'
      JWT_SECRET: jwt-secret
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - hardhat
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  hardhat:
    container_name: hardhat
    build:
      dockerfile: Dockerfile.hardhat
      context: .
    image: hardhat
    ports:
      - '8545:8545'
    restart: always
    volumes:
      - ./hardhat/contracts:/app/contracts
      - ./hardhat/scripts:/app/scripts

volumes:
  postgres_volume:
