version: '3'

services:
  xyz:
    container_name: xyz
    build:
      context: .
    image: xyz
    environment:
      NODE_ENV: development
      PORT: 3000
      LOG_LEVEL: log
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres-db
      DB_USER: postgres-user
      DB_PASSWORD: postgres-password
      HARDHAT_RPC_URL: 'http://hardhat:8545'
      ETHEREUM_RPC_URL:
      POLYGON_RPC_URL:
      JWT_SECRET: jwt-secret
      JWT_ISSUER: xyz
      JWT_EXPIRES_IN: 7d
      THROTTLE_TTL_SECS: 1
      THROTTLE_LIMIT: 5
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - hardhat

  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
    ports:
      - '5050:80'
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

  hardhat:
    container_name: hardhat
    build:
      context: ./hardhat
    image: hardhat
    ports:
      - '8545:8545'
    volumes:
      - ./hardhat/contracts:/hardhat/contracts
      - ./hardhat/scripts:/hardhat/scripts

volumes:
  postgres_volume:
  pgadmin_volume:
