services:
  xyz:
    container_name: xyz
    build:
      context: .
    profiles:
      - all
    environment:
      NODE_ENV: development
      PORT: 3000
      LOG_LEVEL: log
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres-db
      DB_USER: postgres-user
      DB_PASSWORD: postgres-password
      HARDHAT_RPC_URL: 'http://hardhat:8545'
      ETHEREUM_RPC_URL: 'https://ethereum.publicnode.com'
      POLYGON_RPC_URL: 'https://polygon-rpc.com'
      MULTIVAC_RPC_URL: 'https://rpc.mtv.ac'
      JWT_SECRET: jwt-5ecr3t
      JWT_ISSUER: xyz
      JWT_EXPIRES_IN: 7d
      THROTTLE_TTL_SECS: 1
      THROTTLE_LIMIT: 5
      USE_SWAGGER: true
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - postgres
      - hardhat

  postgres:
    container_name: postgres
    image: postgres:16.1
    profiles:
      - dev
      - all
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    profiles:
      - dev
      - all
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

  hardhat:
    container_name: hardhat
    build:
      context: ./hardhat
    profiles:
      - dev
      - all
    ports:
      - '8545:8545'
    restart: on-failure
    volumes:
      - ./hardhat/contracts:/hardhat/contracts
      - ./hardhat/scripts:/hardhat/scripts

volumes:
  postgres_volume:
  pgadmin_volume:
